name: Go  # The name of the workflow that will appear on Github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # needed for updating badge with coverage

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: [1.18, 1.26]
    steps:
    - name: Check out PR branch
      uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 0

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...
        go tool cover -func coverage.out -o coverage.out  # Replaces coverage.out with the analysis of coverage.out

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v3
      if: ${{ runner.os == 'Linux' && matrix.go == '1.18' }} # Runs this on only one of the ci builds.
      with:
        green: 80
        filename: coverage.out

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v16
      id: verify-changed-files
      with:
        files: README.md

    - name: Commit changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "chore: Updated coverage badge."

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref || github.ref_name }}    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   id: auto-commit-action
    #   with:
    #     commit_message: Apply Code Coverage Badge
    #     skip_fetch: true
    #     skip_checkout: true
    #     file_pattern: ./README.md

    # - name: Push Changes
    #   if: steps.auto-commit-action.outputs.changes_detected == 'true'
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ github.token }}
    #     branch: ${{ github.ref }}
